# PBS flags
queue: normal
project: fp0
walltime: 1:00:00
ncpus: 960
qsub_flags: -l other=hyperthread

# Misc
#repeat: True
collate: False
stripedio: True

# Model config
model: mom
exe: mom_sis_ncpar_debug
input:
    - core_nyf_forcing
    - gfdl_nyf_1080

mpi:
    module: openmpi/1.10.2
